### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jacky96623**
Updated links for example flow of preparations for password reset request from a registered user, trying to sync the lines highlighted with the content.

#### Related issues

- connect to <link_to_referenced_issue>

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by dhmlau** [comment]
@jacky96623, thanks for the PR! Your changes LGTM.  Could you please take care of the following things to move forward:
1. Sign the CLA https://cla.strongloop.com/agreements/strongloop/loopback-example-user-management
2. Fix the commit linter error
```
Update README.md: line 3 longer than 72 characters.
```

Please refer to our commit message guideline for details: https://loopback.io/doc/en/contrib/git-commit-messages.html.
To change the commit message, you can use `git commit --amend` command. 
 See documentation: https://help.github.com/en/articles/changing-a-commit-message

**Comment by jacky96623** [comment]
@dhmlau Sorry for the mistakes. Should be ok now. Please let me know if there is any other problem.

**Comment by dhmlau** [comment]
Thanks @jacky96623 for your contribution.  Your PR has landed! 🎉

**Pull request merged**
